### ISSUE TITLE
Is there a pure C wrapper?

### ISSUE THREAD

**Issue by cogmeta** [d99kris/spacy-cpp#1]
If not, can you please guide us? Thanks.

**Comment by d99kris** [comment]
I'm not aware of any C wrapper for spaCy. You could read the code for this project `spacy-cpp` to get an idea of what type of work is needed for a C wrapper.

**Comment by d99kris** [comment]
No idea, sorry. I've never used GRPC. Perhaps there's some log to look at, or maybe GDB/LLDB can be attached to the process to check where it's stuck. However, I googled GRPC, and it seems it supports Python, so perhaps it's easier to directly interface with the official spaCy API?

**Comment by cogmeta** [comment]
Thanks @d99kris . We need to integrate it into c++ server that does lot of stuff on top of parsed results. We have already have GRPC python server as you suggested but we want to get rid of the remote api call and do the parsing in the c++ code itself. Thanks, anyway,

**Comment by d99kris** [comment]
Ok got it. Good luck! I'll close this issue, but feel free to open another if you have some specific issue.

**Comment by cogmeta** [comment]
Thanks. Will report back if we find the issue and the solution.

**Comment by BennyDietrich** [comment]
Hi @cogmeta I've tried to multithread spacy-c++ myself but I could run it on multiple threads concurrently. Did you manage to do that in your implementation or did you just share the GIL between the threads? I hope this doesn't come way to late.
