### ISSUE TITLE
Windows build?

### ISSUE THREAD

**Issue by belal-sweileh** [d99kris/spacy-cpp#14]
Hi,

Is there a Windows build? Are there steps to follow to for Windows? Please advise. Thanks!

**Comment by d99kris** [comment]
Hi,
There's no Windows build available, nor any platform-specific steps for Windows.

If you're looking to just try the library out, I think using it as a header-only library should be fairly straight-forward, see
https://github.com/d99kris/spacy-cpp#header-only-library

You'll also need to install `spaCy` and a model, something like this at the command prompt:
```
pip3 install -U spacy
python3 -m spacy download en_core_web_sm
```

I'm not sure if Visual Studio requires any special steps to find the python installation.

Perhaps you can try it out and see if it works? I don't have a Windows machine available right now, but I could maybe get a chance to try it out in the weekend.

**Comment by d99kris** [comment]
Hi again,
I got a chance to try this out now. Here are the steps (tested on Windows 10, VS 2019 Community).

1. Install Python from https://www.python.org/downloads/ and ensure python is added to PATH
2. Open command prompt `cmd.exe` and run:
```
pip3 install -U spacy
python -m spacy download en_core_web_sm
```

3. Open VS 2019, create a C++ "Console App" project.
4. Download `spacy-cpp` from https://github.com/d99kris/spacy-cpp/archive/refs/heads/master.zip and extract the archive.
5. Copy the folder `spacy` from `spacy-cpp`'s `src` folder, to the VS project folder, ex: `c:\Users\Kris\source\repos\SpacyTest\spacy` 
6. Switch project target to "Release" and "x64".
7. Add Python include and libs paths to the project (adjust actual path depending on where Python was installed in step 1). Go to Project Properties -> Configuration Properties -> VC++ Directories. In `Include Directories`, add at the end:
```
;c:\Program Files\Python310\include\
```
In `Library Directories`, add at the end:
```
;c:\Program Files\Python310\libs\
```

8. Use the following code to test:
```c++
#include <iostream>

#define SPACY_HEADER_ONLY
#include "spacy/spacy"

int main()
{
    Spacy::Spacy spacy;
    auto nlp = spacy.load("en_core_web_sm");
    auto doc = nlp.parse("This is a sentence.");
    for (auto& token : doc.tokens())
        std::cout << token.text() << " [" << token.pos_() << "]\n";
}
```
9. Press F5 to build and run.

Will proceed to close this issue, but feel free to re-open for follow-up questions.

**Comment by belal-sweileh** [comment]
Hi, 

Thanks for your reply. I gave it a try, and it worked! 

What steps would be needed to embed python and spacy into the C++ application so that it can be used on a machine without Python or Spacy installed and without the language model downloaded? Would I have to use an [embeddable version]( https://www.python.org/ftp/python/3.10.8/python-3.10.8-embed-amd64.zip) of python on Windows for this and add the required python packages? Or perhaps freeze everything into an executable using PyInstaller? Please advise. Thanks.

**Comment by d99kris** [comment]
Hi again, sorry I don't know how to do that. I believe for Python itself one can probably distribute python.lib / libpython.so along with the executable (or link statically). But for Python packages (such as `spacy` - and its models) I have no idea.
