### ISSUE TITLE
Adding this as a library in bazel is creating segmentation fault(core dumped) error

### ISSUE THREAD

**Issue by dbanka** [d99kris/spacy-cpp#3]
I don't know if you have worked with bazel or not but if you could help me make it work in bazel then it would be awesome. Thanks.

This is the build file I am using for spacy:
```
cc_library(
    name = "spacy",
    srcs=["attrs.cpp", "doc.cpp", "nlp.cpp", "pyobjectptr.cpp", "python.cpp", "spacy.cpp", "span.cpp", "stringstore.cpp", "token.cpp", "vocab.cpp"],
    hdrs =["attrs.h","doc.h","nlp.h","pyobjectptr.h","python.h","spacy.h","span.h","stringstore.h","token.h","vocab.h"],
    visibility= ["//visibility:public"],
    copts = ["-std=c++11"],
)

```
In my main proj build file , I am adding this as a dependency:
//spacy:spacy

And in my project files
I am including them as 
#include "attrs.h"
#include "doc.h"
#include "nlp.h"
#include "pyobjectptr.h"
#include "python.h"
#include "spacy.h"
#include "span.h"
#include "stringstore.h"
#include "token.h"
#include "vocab.h"

But when the code reaches the line:
Spacy::Spacy spacy;

It is giving error 
> Segmentation fault(Core dumped)

**Comment by d99kris** [comment]
Hi @dbanka 

I tried to create a bazel project quickly, but I have no previous experience and I'm failing already at the compilation step (cannot find Python.h with my WORKSPACE and BUILD hack). 

Could you please help share the relevant files you're using? Preferably a zip or tar-ball of the whole project, and the build command you're using? 

This way I can reproduce your issue faster, and hopefully be able to help. Thanks!

**Comment by dbanka** [comment]
Hi @d99kris I tried making a basic bazel project to show you the process. Turned out that spacy-cpp works with bazel too. So, it must have been some issue with the code of my main project. You can get the basic bazel project with spacy-cpp [here](https://drive.google.com/file/d/14BcmK1XmPHS8EJ78o7hAnW49LFrGd3AC/view?usp=sharing)

**Comment by d99kris** [comment]
That's great to hear! Thanks for sharing the project!
