### ISSUE TITLE
The connection between the two tokens is then established

### ISSUE THREAD

**Issue by BalLooN1874** [d99kris/spacy-cpp#4]
I want use spacy-cpp establish a connection between two tokens,  
It 's my browse https://explosion.ai/demos/displacy，
for example:  ”displaCy“ and "uses”  the relationship between the two words is: “nsubj”,  in spacy-cpp， how to build the relationship?

**Comment by d99kris** [comment]
https://explosion.ai/demos/displacy is a visualization of dependency tagging, so one can simply use the `dep_` member of `token`, in either spacy or spacy-cpp, to get this information. Here's a simple C++ snippet to do dependency tagging:
```c++
#define SPACY_HEADER_ONLY
#include <spacy/spacy>
#include <iostream>

int main()
{
  Spacy::Spacy spacy;
  auto nlp = spacy.load("en_core_web_sm");
  auto doc = nlp.parse("displaCy uses JavaScript, SVG and CSS to show you how computers understand language");
  for (auto& token : doc.tokens())
  {
    std::cout << token.text() << " [" << token.dep_() << "] ";
  }
  std::cout << std::endl;

  return 0;
}
```
The expected output would be:
```
displaCy [nsubj] uses [ROOT] JavaScript [dobj] , [punct] SVG [conj] and [cc] CSS [conj] to [aux] show [xcomp] you [dobj] how [advmod] computers [nsubj] understand [ccomp] language [dobj] 
```
Hope this helps!

**Comment by BalLooN1874** [comment]
Thank you for your reply，It helps me a lot。
