### ISSUE TITLE
Would iOS Support Be Possible?

### ISSUE THREAD

**Issue by KTRosenberg** [d99kris/spacy-cpp#8]
Out of curiosity, can you imagine any way in which we could embed python and run your library on iOS? I currently use an external Python server to generate spacy output that I send back to the client, but it would be great to keep everything on-device. If it’s possible, would it be worth it? It would definitely need to run in a background thread. I also think the model might be an issue since it’s unclear where that would be stored/how it would be accessed. I’m not sure if an ios device could handle all of this.

**Comment by d99kris** [comment]
Hi @KTRosenberg - that's a good question. 

So `spacy-cpp` is simply a wrapper for `spacy` (which is implemented in Python / Cython). The tricky part is most likely building `spacy` itself for iOS. It appears it could be possible, possibly leveraging https://github.com/beeware/Python-Apple-support but there is no off-the-shelf solution available AFAIK. 

I would imagine an iOS device has sufficient computational power, but I think it could be quite a bit of work to do the iOS integration/building of python + spacy + spacy's dependencies. 

Unfortunately it's outside the scope of the `spacy-cpp` project. But we can leave this issue open for a while in case someone else has inputs on building `spacy` for iOS.

**Comment by d99kris** [comment]
Will proceed to close this issue as there are no plans for spacy-cpp to include this in its scope, and there hasn't been any input from others either on building `spacy` itself for iOS.
