### ISSUE TITLE
No module named spacy. Try: pip install -U spacy

### ISSUE THREAD

**Issue by ZzoxAA** [d99kris/spacy-cpp#9]
I got this when I want to instantiate a Spacy object. But I'm sure I have installed spacy and I can run `python -m spacy` correctly. Cloud you please provide some possible reasons for this situation？

**Comment by d99kris** [comment]
Hi! 
Let me first check, is the issue title exactly matching the error message you are seeing (older versions of spacy-cpp had such message, but recent versions suggests user to use `pip3`)? If yes, please try latest spacy-cpp.

Can your system access Spacy in Python? Like for example the Python code in https://github.com/d99kris/spacy-cpp#example-usage

If yes, I suspect there could be some mismatch between for which Python version Spacy is installed for, and which Python version you are building spacy-cpp for. By default spacy-cpp's CMakeLists.txt uses Python v3.x, so spacy needs to be installed for Python 3 (e.g. using `pip3`). Alternatively one can change spacy-cpp's CMakeLists.txt to build for Python 2 (not recommended as Python 2 is EOL) by changing:
```find_package(PythonLibs 3 REQUIRED)
find_package(PythonInterp 3 REQUIRED)```
to
```find_package(PythonLibs 2.7 REQUIRED)
find_package(PythonInterp 2.7 REQUIRED)```
and rebuild (maybe delete `build` dir first, just in case).

If still no success, perhaps you can share more system details such as version of OS, Python, CMake, C++ Compiler. Thanks!

**Comment by d99kris** [comment]
I believe the above steps should help resolving the issue, so I will proceed to close this issue. Feel free to re-open it for follow-up questions. Thanks!

**Comment by nuttyartist** [comment]
I'm getting the same error after building the header only example. 

I'm running `./exprog1`
And get:
```
libc++abi: terminating with uncaught exception of type std::runtime_error: No module named spacy. Try: pip3 install -U spacy
Abort trap: 6
```
